include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "lib/src/native/bindings.dart"

  errors:
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
    parameter_assignments: ignore
    use_string_in_part_of_directives: ignore
    always_put_required_named_parameters_first: ignore
